### PR TITLE
LaTeX template

### PR DESCRIPTION
**Pull request by marado**

### CODE REVIEW

**Comment by tcarreira** [comment]
How should I compile this to get a PDF version? (command line)

**Comment by marado** [comment]
`xelatex Ubucon.Sintra.2019.tex` will generate an `Ubucon.Sintra.2019.pdf`.

**Comment by tcarreira** [comment]
Hey @marado, sorry for taking so long to get to you.

I tried to run it, but I got an error:
```
*** you should *not* be loading the inputenc package
*** XeTeX expects the source to be in UTF8 encoding
*** some features of other encodings may conflict, resulting in poor output.
No file Ubucon.Sintra.2019.nav.

Overfull \hbox (4.24799pt too wide) in paragraph at lines 22--22
[][] 
<use  "bg-title.png" > <use  "bg-slides.png" > [1]
(/usr/share/texlive/texmf-dist/tex/latex/euenc/eu1lmtt.fd)
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsb.fd)
! Undefined control sequence.
\@includesvg ...ifnum \pdfstrcmp {\pdffilemoddate 
                                                  {\SVG@in@path #2.svg}}{\pd...
l.51 \end{frame}
``` 

The output was a single page with the first slide.
Do you know what the problem is?


You can see the full log here: https://pastebin.ubuntu.com/p/8xPpqKmdRW/

**Comment by marado** [comment]
No file missing: I didn't have time to check out your log carefully, but I seem to have a few dependencies present in my system that you have not, even if I didn't see on your log what can be causing the generation of just one slide.

If you wish to compare them yourself, here's my own log (generating a 9 pages PDF):
[Ubucon.Sintra.2019.log](https://github.com/ubuconeurope/2019sintra-presentation-template/files/6230051/Ubucon.Sintra.2019.log)

**Comment by tcarreira** [comment]
Oh, I did it. 
I was using an old version of latex :/ 
Working now (i think)

I'm gonna merge this MR and then I will add a Dockerfile so we can reproduce this build again ;) 

Thank you for the hard work :+1:

**Pull request merged**
